### ISSUE TITLE
Given a user id lookup the thunderbird profile

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/pyThunderbird#2]
use a yaml file for configuration
```yaml
#
# Thunderbird profiles mapping 
#
wf:
  db: /Users/wf/backup/global-messages-db.sqlite
  profile: /Users/wf/Library/Thunderbird/Profiles/mxz53xfn.default
```
